### ISSUE TITLE
Makefile to build and launch

### ISSUE THREAD

**Issue by matteovidali** [malintha/multi_uav_simulator#15]
Hey, 
I have made a [Makefile](https://gist.github.com/matteovidali/caab443e66425e260b6a1c1bd842d28c) for this project that will handle the dependencies required as well as the build process. This is the first version of the Makefile, and it works on a fresh install of Ubuntu `20.04.5`, Kernel: `5.15.0-67-generic`. 

To use this file, first download the gist, and place it the directory where you would like your `catkin_ws` to be made. 
Then run `make deps` to install dependencies required. This will only work on distros and versions that support ROS1, and I have only tested it on 1 machine, so it will be updated as required. 

Next, run `make build` to build the multi_uav_simulator.
Finally, run `make launch` to launch the simulation, and an Rviz window should open.

Included is a `make clean` command, to remove the entire `catkin_ws`.

Please leave comments either here and mention me (@matteovidali) with updates, or place requests on the gist itself.

**Comment by malintha** [comment]
Hi @matteovidali,

Kudos on the script for managing the dependencies. I think we can bundle this with the repository eventually. I have a few comments however, especially on reinstalling those dependencies that comes standard to ros.

- Lets get rid of the ros-noetic installation at https://gist.github.com/matteovidali/caab443e66425e260b6a1c1bd842d28c#file-makefile-L6. We can safely assume that any users might have ros noetic/melodic installed already. In that case this could potentially cause conflicts.
- I'm not sure why we need `python3-catkin-lint` here. I don't think it'd cause any harm either, just curious.
- There is an additional `python3-pip` argument.
- This shouldn't depend on `python3-rosdep2`, since we are already using wstool. In my experience it has caused to reinstall packages like `ros-noetic-tf` which typically comes standard with the ros full desktop installation (https://github.com/malintha/multi_uav_simulator/issues/14#issuecomment-1318971613).
- The dependencies at https://gist.github.com/matteovidali/caab443e66425e260b6a1c1bd842d28c#file-makefile-L25 come standard with the ros-desktop-full installation. We don't have to install them again.

**Comment by malintha** [comment]
The `clean` command shouldn't erase the whole `catkin_ws`. At best it should only erase the `devel`, `build` and `logs` directories inside the catkin_ws. Automating this can cause the false implication that it would only "clean" mavswarm, when erasing all the built packages inside the workspace. So, I think it's best to remove the clean command.

**Comment by malintha** [comment]
@matteovidali For development and simulation I would totally recommend ros desktop full installation. The base (or bare bone) installation is mostly targeted for running inside the robot computing boards; some of them are in fact incompatible for full desktop installation.

Yes, I think a full installation might solve this issue. Let's give it a try. Please make a PR when you are done with the changes. :)
